import Header from '@/components/Header'
import '../../styles/globals.css'
import { Inter } from 'next/font/google'
import ImageGallery from '@/components/ImageGallery'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Images',
  description: 'Generated by create next app',
}

export default function MyImagesLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <ImageGallery />
    </>
  )
}
